services:
  pgadmin:
    image: dpage/pgadmin4:latest
    ports:
      - ${DB_ADMIN}:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=${DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${DEFAULT_PASSWORD}
    volumes:
      - pgadmin_vol:/var/lib/pgadmin
    networks:
      - database_network
  
  db_postgre:
    image: postgres:latest
    ports:
      - ${DB_PORT}:5432
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - database_vol:/var/lib/postgresql/data
    networks:
      - database_network
    
  jenkins :
    ports:
      - ${JENKINS_AP}:50000
      - ${JENKINS_WP}:8080
    build: .
    container_name: jenkins_paketlengkap
    networks:
      - database_network
  
volumes:
  pgadmin_vol:
  database_vol:
networks:
  database_network: