services:
  pgadmin:
    image: dpage/pgadmin4:latest
    ports:
      - 8081:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=${DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${DEFAULT_PASSWORD}
    volumes:
      - pgadmin_vol:/var/lib/pgadmin
    networks:
      - database_network
  
  db_postgre:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - database_vol:/var/lib/postgresql/data
    networks:
      - database_network
  
  jenkins:
    image: jenkins-jdk-17
    container_name: jenkins-jdk-17
    user: root
    restart: always
    ports:
      - 8080:8080
      - 50000:50000
    volumes:
      - jenkins_home:/var/jenkins_home

volumes:
  pgadmin_vol:
  database_vol:
  jenkins_home:
networks:
  database_network: