pipeline {
    agent any
    environment {
                    dbms = 'postgresql'
                    tbname = 'data_hotel'
                    dbname = 'cobaaja'
                    USER = credentials('user')
                    HOST = credentials('host')
                    PASS = credentials('password')
                    PORT = credentials('port')
                }

    stages {
        stage('Run Python') {
            steps {
                sh ('python3 main.py -db $dbms -u $USER -hs $HOST -ps $PASS -p $PORT -n $dbname -tb $tbname')
            }
        }
    }

    post {
        always {
            mail to: 'dimasega1811@gmail.com',
                 subject: "Jenkins Build Notification: ${currentBuild.fullDisplayName}",
                 body: """\
                 Build Status: ${currentBuild.currentResult}
                 Project: ${env.JOB_NAME}
                 Build Number: ${env.BUILD_NUMBER}
                 Build URL: ${env.BUILD_URL}
                 """
        }
    }   
}