pipeline {
    agent any
    environment {
                    dbms = 'postgresql'
                    tbname = 'data_hotel'
                    dbname = 'cobaaja'
                    USER = credentials('user')
                    HOST = credentials('host')
                    PASS = credentials('password')
                    PORT = credentials('port')
                }

    stages {
        stage('Run Python') {
            steps {
                sh ('python3 main.py -db $dbms -u $USER -hs $HOST -ps $PASS -p $PORT -n $dbname -tb $tbname')
            }
        }
    }

    post {
        always {
            def buildStatus = currentBuild.currentResult
            def projectName = env.JOB_NAME
            def buildNumber = env.BUILD_NUMBER
            def buildUrl = env.BUILD_URL

        emailext(
            body: """Build Status : ${buildStatus}
            Project : ${projectName} 
            Build Number: ${buildNumber}
            Build URL: ${buildUrl}""",
            subject: 'From Jenkins Pipeline',
            to: 'your.email@example.com')
        }
    }   
}